-- V104: Create delivery_sheet_snapshots table
-- Nightly snapshot generated by DeliverySheetGenerationJob.
-- Replaced (not appended) on job rerun — one snapshot per delivery date.

CREATE TYPE delivery_sheet_source AS ENUM ('SCHEDULER', 'ADMIN_RERUN');

CREATE TABLE delivery_sheet_snapshots (
    id                   UUID                   NOT NULL DEFAULT gen_random_uuid(),
    delivery_date        DATE                   NOT NULL,
    generated_at         TIMESTAMPTZ            NOT NULL DEFAULT NOW(),
    generated_by_source  delivery_sheet_source  NOT NULL,
    generated_by_user_id UUID                   NULL,
    snapshot_json        JSONB                  NOT NULL,

    CONSTRAINT pk_delivery_sheet_snapshots PRIMARY KEY (id),
    CONSTRAINT uq_delivery_sheet_snapshots_date UNIQUE (delivery_date)
);
